name: StartTech-application

on:
  push:
    branches:
      - main
    paths:
      - "starttech-application/Client/**"

jobs:
  build:
    name: Build and Test Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: starttech-application/Client/package-lock.json

      - name: Install dependencies
        working-directory: starttech-application/Client
        run: npm ci

      - name: Run unit tests  (if present)
        working-directory: starttech-application/Client
        run: |
          npm test -- --watch=false || echo "Test not Found"

      - name: Security scan (npm audit)
        working-directory: starttech-application/Client
        run: npm audit --audit-level=high --force || echo "High severity vulnerabilities found, check manually"

      - name: Build production
        env:
          VITE_API_BASE_URL: ${{secrets.VITE_API_BASE_URL}}
        working-directory: starttech-application/Client
        run: npm run build
        

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: starttech-application/Client/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'ref/heads/main'
    name:  Deploy Frontend


    steps: 
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4

        with:

          name: react-build
          path: starttech-application/Client/dist
          
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:

          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Deploy to S3
        run: |
            aws s3 sync starttech-application/Client/dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete


      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
            
          
       
        
