name: StartTech-application

on:
  push:
    branches:
      - main
    # paths:
    #   - "Client/**"

jobs:
  build:
    name: Build and Test Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Client/package-lock.json

      - name: Install dependencies
        working-directory: Client
        run: npm ci

      - name: Run unit tests
        working-directory: Client
        run: npm test -- --watch=false

      - name: Security scan (npm audit)
        working-directory: Client
        run: npm audit --audit-level=high

      - name: Build production
        working-directory: Client
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: Client/dist
