name: StartTech-application

on:
  push:
    branches:
      - main
    paths:
      - "starttech-application/Client/**"

jobs:
  build:
    name: Build and Test Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: starttech-application/Client/package-lock.json

      - name: Install dependencies
        working-directory: starttech-application/Client
        run: npm ci

      - name: Run unit tests  (if present)
        working-directory: starttech-application/Client
        run: |
          npm test -- --watch=false || echo "Test not Found"

      - name: Security scan (npm audit)
        working-directory: starttech-application/Client
        run: npm audit --audit-level=high

      - name: Build production
        working-directory: starttech-application/Client
        run: npm run build
        

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: starttech-application/dist
